apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: nati
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
  serviceAccountName: nati-service-account
