apiVersion: v1
kind: Pod
metadata:
  name: cyerspod
  namespace: nati  # Ensure the namespace is correct
spec:
  serviceAccountName: cyerspod-sa  # Attach the ServiceAccount
  containers:
  - name: simple-container
    image: busybox  # Use the simplest container image available
    command: ["sh", "-c", "sleep 3600"]  # Keep the container running
    securityContext:
      allowPrivilegeEscalation: false  # Comply with PodSecurity policies
      runAsNonRoot: true  # Ensure the container does not run as root
      capabilities:
        drop: ["ALL"]  # Drop all unnecessary capabilities
      seccompProfile:
        type: RuntimeDefault  # Use the default seccomp profile
