apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyetest-sa
  namespace: nati  # <change>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cyetest-admin-binding
subjects:
- kind: ServiceAccount
  name: cyetest-sa
  namespace: nati  # <change>
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: cyetest-token
  namespace: nati  # <change>
  annotations:
    kubernetes.io/service-account.name: cyetest-sa  
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Pod
metadata:
  name: cyetest
  namespace: nati  # <change>
spec:
  serviceAccountName: cyetest-sa  
  containers:
  - name: simple-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"] 
    securityContext:
      allowPrivilegeEscalation: false  
      runAsNonRoot: true
      runAsUser: 1000  
      capabilities:
        drop: ["ALL"] 
      seccompProfile:
        type: RuntimeDefault  
