apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyerspod-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cyerspod-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cyerspod-sa
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Grants full admin privileges
  apiGroup: rbac.authorization.k8s.io

---
