apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyerspod-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cyerspod-admin-binding
subjects:
- kind: ServiceAccount
  name: cyerspod-sa
  namespace: nati  # Specify the correct namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Grants full admin privileges
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: cyerspod-token
  namespace: nati  # Ensure this is the correct namespace
  annotations:
    kubernetes.io/service-account.name: cyerspod-sa  # Link to the service account
type: kubernetes.io/service-account-token

